# Generated by Django 4.0.5 on 2022-06-14 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('importance', models.IntegerField(validators=[django.core.validators.MinValueValidator(-10), django.core.validators.MaxValueValidator(100)])),
                ('example_sentence', models.TextField()),
                ('meaning', models.TextField()),
                ('note', models.TextField()),
                ('thesis_id', models.IntegerField()),
                ('pronounce_id', models.IntegerField()),
                ('phonetics_id', models.IntegerField()),
                ('meaning_id', models.IntegerField()),
            ],
            options={
                'ordering': ['-importance'],
            },
        ),
    ]
