# Generated by Django 4.0.5 on 2022-06-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='example_sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
