# Generated by Django 4.0.5 on 2022-06-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_alter_word_example_sentence_alter_word_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='meaning_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='phonetics_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronounce_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='thesis_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
